# Setup
title:        Code Avenger
tagline:      Random thoughts about code and technology
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Marian Veteanu
  url:        http://linkedin.com/in/mveteanu 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown